const writingProjects = [
    {
        title: "Coming soon!",
        description: "Writing samples will be added here.",
        category: "None",
        link: "#"
    }
];


const softwareProjects = [
    {
        title: "The Ledger",
        description: "A work-in-progress calculator I'm adding to based off of an Excel Spreadsheet as I complete an accounting program at Bristol Community College.",
        image: "images/TheLedgerImage.PNG",
        demo: "software/The-Ledger-Financial-Calculators.html",
        github: "#"
    },
    {
        title: "ASCII Sudoku",
        description: "A small sudoku app, built with Google Admob integration. Mathematically autogenerated music, intended to be simple yet somewhat creepy as part of a larger project. HTML code.",
        image: "images/SS2.PNG",
        demo: "software/ascii_sudoku.html",
        github: "#"
    },
    {
        title: "TabOut",
        description: "A terminal meant to run underneath full screen applications, allowing keyboard inputs to control Spotify without having to \"tab out\". Uses Python.",
        image: "images/taboutimage.PNG",
        demo: "#",
        github: "https://github.com/jexjackson98-prog/TabOut/tree/main/TabOut%20-%20PublicCopy"
    },
    {
        title: "Indeed Sweeper",
        description: "Indeed has a lot of spam listings. This is a Google Extension that allows you to block companies you've determined are such.",
        image: "images/indeedsweeperimage.PNG",
        demo: "#",
        github: "https://github.com/jexjackson98-prog/IndeedSweeper/tree/main/Indeed%20Sweeper"
    }
];