const writingProjects = [
    {
        title: "Should You Play Genshin Impact?",
        description: "A piece written more casually, with the passion of a personal hobby.",
        tags: ["Articles"],
        link: "writing/articles/Should%20You%20Play%20Genshin%20Impact.pdf"
    },
    {
        title: "How To Paint An AR15",
        description: "A published, informal guide written on a subject I lack personal experience in with SEO key-term integration.",
        tags: ["Articles"],
        link: "writing/articles/983FC7BB_1%20_%20How%20To%20Paint%20An%20AR15%20(Full%20DIY%20Guide%20With%20Ideas)%20(2).pdf"
    },
    {
        title: "Google's New Android App Requirements",
        description: "A small blurb notifying and explaining Google Play Store's annually updated requirements.",
        tags: ["Articles"],
        link: "writing/articles/Google%20Will%20Require%20Android%2016%20Compatibility%20for%20New%20Play%20Store%20Submissions%20in%202026.pdf"
    },
    {
        title: "Best Minigolf in Brooklyn",
        description: "Another published, casually-toned guide on a subject I had no prior information on, including SEO key-term integration. Note that there were not eight mini-golf locations available to choose from, the buyer simply asked for such, so I was forced to include a bar which happened to have a small, single hole.",
        tags: ["Articles"],
        link: "writing/articles/Best%20Minigolf%20in%20Brooklyn%20(1).pdf"
    },
    {
        title: "Chapter 7 vs Chapter 13 Bankruptcy",
        description: "An explanation of the differences between these two types of bankruptcy, written after reading the full definition of each on a .gov source.",
        tags: ["Essays"],
        link: "writing/essays/Ch7%20Ch%2013%20Bankruptcy.pdf"
    },
    {
        title: "What Affects Interest Rates?",
        description: "An essay on what economic situations impact a bank's decision to raise or lower loan interest rates.",
        tags: ["Essays"],
        link: "writing/essays/JJackson%20CH%206%20Essay%20(1).pdf"
    },
    {
        title: "The Difference Between Finance and Accounting",
        description: "Another essay, written more subjectively than the previous two.",
        tags: ["Essays"],
        link: "writing/essays/JJackson%20CH2%20Essay%20(2).pdf"
    },
    {
        title: "Plumbing Services",
        description: "A published work for a New Jersey plumbing company advertising tankless water heaters with SEO key-term integration.",
        tags: ["Etc"],
        link: "writing/etc/49B72A43_5%20_%20Plumbing%20Services%20_%20Tankless%20Water%20Heater.pdf"
    },
    {
        title: "AdThrive Requirements [2022]",
        description: "A published blog article, ultimately promoting AdThrive as a way to promote blogs, with SEO key-term integration.",
        tags: ["Etc"],
        link: "writing/etc/D76BDFA4_5%20_%20AdThrive%20requirements%20%5B2022%5D%20(1).pdf"
    }
];


const softwareProjects = [
    {
        title: "The Ledger",
        description: "A work-in-progress calculator I'm adding to based off of an Excel Spreadsheet as I complete an accounting program at Bristol Community College. HTML code.",
        image: "images/TheLedgerImage.PNG",
        demo: "software/The-Ledger-Financial-Calculators.html",
        github: "#"
    },
    {
        title: "ASCII Sudoku",
        description: "A small sudoku app, built with Google Admob integration. Mathematically autogenerated music, intended to be simple yet somewhat creepy as part of a larger project. HTML code.",
        image: "images/SS2.PNG",
        demo: "software/ascii_sudoku.html",
        github: "#"
    },
    {
        title: "TabOut",
        description: "A terminal meant to run underneath full screen applications, allowing keyboard inputs to control Spotify without having to \"tab out\". Uses Python.",
        image: "images/taboutimage.PNG",
        demo: "https://github.com/jexjackson98-prog/TabOut/tree/main/TabOut%20-%20PublicCopy",
        github: "#"
    },
    {
        title: "Indeed Sweeper",
        description: "Indeed has a lot of spam listings. This is a Google Extension that allows you to block companies you've determined are such.",
        image: "images/indeedsweeperimage.PNG",
        demo: "https://github.com/jexjackson98-prog/IndeedSweeper/tree/main/Indeed%20Sweeper",
        github: "#"
    }
];